---
title: "K-Medias"
subtitle: "Machine learning essential training"
author: "DiplomadosOnline.com"
date: "Marzo, 2023"
output:
    rmarkdown::html_document:
      theme: lumen
      toc: true
      toc_depth: 2
      toc_float: true
---

```{r}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
library(ggplot2)
library(factoextra)
library(mclust)
library(cluster)
```

```{r}
df <- read.csv("retail.csv")
df <- scale(log(df))
head(df)
```

```{r}
fviz_nbclust(df, kmeans, method = "wss") +
geom_vline(xintercept = 7, linetype = 2)
```

```{r}
km.res <- kmeans(df, 6, nstart = 25)
aggregate(df, by=list(cluster=km.res$cluster), mean)
dd <- cbind(df, cluster = km.res$cluster)
fviz_cluster(km.res, data = df)
```

```{r}
potential_k <- 1:10
BIC_values <- vector("list", length(potential_k))
for (i in potential_k) {
  BIC_values[[i]] <- Mclust(df, G = i)$bic
}
plot(potential_k, unlist(BIC_values), type = "b")
```

```{r}
gmm_model <- Mclust(df, G = 4)
aggregate(df, by=list(clusterGMM=gmm_model$classification), mean)
fviz_cluster(gmm_model, data = df)
```
